server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Empêcher l'indexation par les moteurs de recherche
    add_header X-Robots-Tag "noindex, nofollow, noarchive" always;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Servir le fichier robots.txt
    location = /robots.txt {
        add_header Content-Type text/plain;
    }
}

server {
    listen 80;
    server_name apps.youvape.fr;

    # Challenge Let's Encrypt
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host:8443$request_uri;
    }
}

server {
    listen 8443 ssl;
    server_name apps.youvape.fr;

    ssl_certificate /etc/letsencrypt/live/apps.youvape.fr/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/apps.youvape.fr/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    add_header X-Robots-Tag "noindex, nofollow, noarchive" always;

    location / {
        proxy_pass http://youvape_backend:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }
}
